In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/mihalcearobertmihail/mede-u18-mhealth/MHEALTHDATASET/README.txt
/kaggle/input/datasets/mihalcearobertmihail/mede-u18-mhealth/MHEALTHDATASET/mHealth_subject1.log
/kaggle/input/datasets/mihalcearobertmihail/mede-u18-mhealth/MHEALTHDATASET/mHealth_subject10.log
/kaggle/input/datasets/mihalcearobertmihail/mede-u18-mhealth/MHEALTHDATASET/mHealth_subject2.log
/kaggle/input/datasets/mihalcearobertmihail/mede-u18-mhealth/MHEALTHDATASET/mHealth_subject3.log
/kaggle/input/datasets/mihalcearobertmihail/mede-u18-mhealth/MHEALTHDATASET/mHealth_subject4.log
/kaggle/input/datasets/mihalcearobertmihail/mede-u18-mhealth/MHEALTHDATASET/mHealth_subject5.log
/kaggle/input/datasets/mihalcearobertmihail/mede-u18-mhealth/MHEALTHDATASET/mHealth_subject6.log
/kaggle/input/datasets/mihalcearobertmihail/mede-u18-mhealth/MHEALTHDATASET/mHealth_subject7.log
/kaggle/input/datasets/mihalcearobertmihail/mede-u18-mhealth/MHEALTHDATASET/mHealth_subject8.log
/kaggle/input/datasets/mihalcearobertmihail/mede-u18-mhealth/MHEALTHDATASET/mHealth_subject9.log
/kaggle/input/datasets/mihalcearobertmihail/mede-u18-pamap2/readme.pdf
/kaggle/input/datasets/mihalcearobertmihail/mede-u18-pamap2/PAMAP2_Dataset/PAMAP2_Dataset/DataCollectionProtocol.pdf
/kaggle/input/datasets/mihalcearobertmihail/mede-u18-pamap2/PAMAP2_Dataset/PAMAP2_Dataset/DescriptionOfActivities.pdf
/kaggle/input/datasets/mihalcearobertmihail/mede-u18-pamap2/PAMAP2_Dataset/PAMAP2_Dataset/PerformedActivitiesSummary.pdf
/kaggle/input/datasets/mihalcearobertmihail/mede-u18-pamap2/PAMAP2_Dataset/PAMAP2_Dataset/readme.pdf
/kaggle/input/datasets/mihalcearobertmihail/mede-u18-pamap2/PAMAP2_Dataset/PAMAP2_Dataset/subjectInformation.pdf
/kaggle/input/datasets/mihalcearobertmihail/mede-u18-pamap2/PAMAP2_Dataset/PAMAP2_Dataset/Optional/subject101.dat
/kaggle/input/datasets/mihalcearobertmihail/mede-u18-pamap2/PAMAP2_Dataset/PAMAP2_Dataset/Optional/subject105.dat
/kaggle/input/datasets/mihalcearobertmihail/mede-u18-pamap2/PAMAP2_Dataset/PAMAP2_Dataset/Optional/subject106.dat
/kaggle/input/datasets/mihalcearobertmihail/mede-u18-pamap2/PAMAP2_Dataset/PAMAP2_Dataset/Optional/subject108.dat
/kaggle/input/datasets/mihalcearobertmihail/mede-u18-pamap2/PAMAP2_Dataset/PAMAP2_Dataset/Optional/subject109.dat
/kaggle/input/datasets/mihalcearobertmihail/mede-u18-pamap2/PAMAP2_Dataset/PAMAP2_Dataset/Protocol/subject101.dat
/kaggle/input/datasets/mihalcearobertmihail/mede-u18-pamap2/PAMAP2_Dataset/PAMAP2_Dataset/Protocol/subject102.dat
/kaggle/input/datasets/mihalcearobertmihail/mede-u18-pamap2/PAMAP2_Dataset/PAMAP2_Dataset/Protocol/subject103.dat
/kaggle/input/datasets/mihalcearobertmihail/mede-u18-pamap2/PAMAP2_Dataset/PAMAP2_Dataset/Protocol/subject104.dat
/kaggle/input/datasets/mihalcearobertmihail/mede-u18-pamap2/PAMAP2_Dataset/PAMAP2_Dataset/Protocol/subject105.dat
/kaggle/input/datasets/mihalcearobertmihail/mede-u18-pamap2/PAMAP2_Dataset/PAMAP2_Dataset/Protocol/subject106.dat
/kaggle/input/datasets/mihalcearobertmihail/mede-u18-pamap2/PAMAP2_Dataset/PAMAP2_Dataset/Protocol/subject107.dat
/kaggle/input/datasets/mihalcearobertmihail/mede-u18-pamap2/PAMAP2_Dataset/PAMAP2_Dataset/Protocol/subject108.dat
/kaggle/input/datasets/mihalcearobertmihail/mede-u18-pamap2/PAMAP2_Dataset/PAMAP2_Dataset/Protocol/subject109.dat

In [2]:
from pathlib import Path
import pandas as pd
import numpy as np

# Paths
MHEALTH_PATH = Path(
    "/kaggle/input/datasets/mihalcearobertmihail/"
    "mede-u18-mhealth/MHEALTHDATASET"
)

PAMAP2_PATH = Path(
    "/kaggle/input/datasets/mihalcearobertmihail/"
    "mede-u18-pamap2/PAMAP2_Dataset/PAMAP2_Dataset"
)

# Files
mhealth_files = sorted(MHEALTH_PATH.glob("mHealth_subject*.log"))
pamap2_files = sorted((PAMAP2_PATH / "Protocol").glob("subject*.dat"))

print("MHEALTH")
print("Number of subjects:", len(mhealth_files))
print("Example:", mhealth_files[0].name)

print("\nPAMAP2")
print("Number of subjects:", len(pamap2_files))
print("Example:", pamap2_files[0].name)

MHEALTH
Number of subjects: 10
Example: mHealth_subject1.log

PAMAP2
Number of subjects: 9
Example: subject101.dat

In [3]:
# Load one subject from each dataset

mhealth_sample = pd.read_csv(
    mhealth_files[0],
    sep=r"\s+",
    header=None
)

pamap2_sample = pd.read_csv(
    pamap2_files[0],
    sep=r"\s+",
    header=None
)

print("MHEALTH shape:", mhealth_sample.shape)
print("PAMAP2 shape:", pamap2_sample.shape)

print("\nMHEALTH sample:")
display(mhealth_sample.head())

print("\nPAMAP2 sample:")
display(pamap2_sample.head())

MHEALTH shape: (161280, 24)
PAMAP2 shape: (376417, 54)

MHEALTH sample:

,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
0,-9.8184,0.009971,0.29563,0.004186,0.004186,2.1849,-9.6967,0.63077,0.103900,-0.84053,...,-8.6499,-4.5781,0.187760,-0.44902,-1.0103,0.034483,-2.35000,-1.610200,-0.030899,0
1,-9.8489,0.524040,0.37348,0.004186,0.016745,2.3876,-9.5080,0.68389,0.085343,-0.83865,...,-8.6275,-4.3198,0.023595,-0.44902,-1.0103,0.034483,-2.16320,-0.882540,0.326570,0
2,-9.6602,0.181850,0.43742,0.016745,0.037677,2.4086,-9.5674,0.68113,0.085343,-0.83865,...,-8.5055,-4.2772,0.275720,-0.44902,-1.0103,0.034483,-1.61750,-0.165620,-0.030693,0
3,-9.6507,0.214220,0.24033,0.079540,0.117220,2.1814,-9.4301,0.55031,0.085343,-0.83865,...,-8.6279,-4.3163,0.367520,-0.45686,-1.0082,0.025862,-1.07710,0.006945,-0.382620,0
4,-9.7030,0.303890,0.31156,0.221870,0.205130,2.4173,-9.3889,0.71098,0.085343,-0.83865,...,-8.7008,-4.1459,0.407290,-0.45686,-1.0082,0.025862,-0.53684,0.175900,-1.095500,0

PAMAP2 sample:

,0,1,2,3,4,5,6,7,8,9,...,44,45,46,47,48,49,50,51,52,53
0,8.38,0,104.0,30.0,2.37223,8.60074,3.51048,2.43954,8.76165,3.35465,...,0.008300,0.009250,-0.017580,-61.1888,-38.9599,-58.1438,1.0,0.0,0.0,0.0
1,8.39,0,NaN,30.0,2.18837,8.56560,3.66179,2.39494,8.55081,3.64207,...,-0.006577,-0.004638,0.000368,-59.8479,-38.8919,-58.5253,1.0,0.0,0.0,0.0
2,8.40,0,NaN,30.0,2.37357,8.60107,3.54898,2.30514,8.53644,3.73280,...,0.003014,0.000148,0.022495,-60.7361,-39.4138,-58.3999,1.0,0.0,0.0,0.0
3,8.41,0,NaN,30.0,2.07473,8.52853,3.66021,2.33528,8.53622,3.73277,...,0.003175,-0.020301,0.011275,-60.4091,-38.7635,-58.3956,1.0,0.0,0.0,0.0
4,8.42,0,NaN,30.0,2.22936,8.83122,3.70000,2.23055,8.59741,3.76295,...,0.012698,-0.014303,-0.002823,-61.5199,-39.3879,-58.2694,1.0,0.0,0.0,0.0

In [4]:
mhealth_columns = [
    "chest_acc_x",
    "chest_acc_y",
    "chest_acc_z",
    "ecg_lead_1",
    "ecg_lead_2",

    "ankle_acc_x",
    "ankle_acc_y",
    "ankle_acc_z",
    "ankle_gyro_x",
    "ankle_gyro_y",
    "ankle_gyro_z",
    "ankle_mag_x",
    "ankle_mag_y",
    "ankle_mag_z",

    "arm_acc_x",
    "arm_acc_y",
    "arm_acc_z",
    "arm_gyro_x",
    "arm_gyro_y",
    "arm_gyro_z",
    "arm_mag_x",
    "arm_mag_y",
    "arm_mag_z",

    "activity"
]

mhealth_sample.columns = mhealth_columns

display(mhealth_sample.head())

,chest_acc_x,chest_acc_y,chest_acc_z,ecg_lead_1,ecg_lead_2,ankle_acc_x,ankle_acc_y,ankle_acc_z,ankle_gyro_x,ankle_gyro_y,...,arm_acc_x,arm_acc_y,arm_acc_z,arm_gyro_x,arm_gyro_y,arm_gyro_z,arm_mag_x,arm_mag_y,arm_mag_z,activity
0,-9.8184,0.009971,0.29563,0.004186,0.004186,2.1849,-9.6967,0.63077,0.103900,-0.84053,...,-8.6499,-4.5781,0.187760,-0.44902,-1.0103,0.034483,-2.35000,-1.610200,-0.030899,0
1,-9.8489,0.524040,0.37348,0.004186,0.016745,2.3876,-9.5080,0.68389,0.085343,-0.83865,...,-8.6275,-4.3198,0.023595,-0.44902,-1.0103,0.034483,-2.16320,-0.882540,0.326570,0
2,-9.6602,0.181850,0.43742,0.016745,0.037677,2.4086,-9.5674,0.68113,0.085343,-0.83865,...,-8.5055,-4.2772,0.275720,-0.44902,-1.0103,0.034483,-1.61750,-0.165620,-0.030693,0
3,-9.6507,0.214220,0.24033,0.079540,0.117220,2.1814,-9.4301,0.55031,0.085343,-0.83865,...,-8.6279,-4.3163,0.367520,-0.45686,-1.0082,0.025862,-1.07710,0.006945,-0.382620,0
4,-9.7030,0.303890,0.31156,0.221870,0.205130,2.4173,-9.3889,0.71098,0.085343,-0.83865,...,-8.7008,-4.1459,0.407290,-0.45686,-1.0082,0.025862,-0.53684,0.175900,-1.095500,0

In [5]:
print("Number of columns:", len(mhealth_sample.columns))

print("\nActivity labels:")
print(
    mhealth_sample["activity"]
    .value_counts()
    .sort_index()
)

print("\nMissing values:")
print(mhealth_sample.isna().sum())

Number of columns: 24

Activity labels:
activity
0     126106
1       3072
2       3072
3       3072
4       3072
5       3072
6       3072
7       3072
8       3379
9       3072
10      3072
11      3072
12      1075
Name: count, dtype: int64

Missing values:
chest_acc_x     0
chest_acc_y     0
chest_acc_z     0
ecg_lead_1      0
ecg_lead_2      0
ankle_acc_x     0
ankle_acc_y     0
ankle_acc_z     0
ankle_gyro_x    0
ankle_gyro_y    0
ankle_gyro_z    0
ankle_mag_x     0
ankle_mag_y     0
ankle_mag_z     0
arm_acc_x       0
arm_acc_y       0
arm_acc_z       0
arm_gyro_x      0
arm_gyro_y      0
arm_gyro_z      0
arm_mag_x       0
arm_mag_y       0
arm_mag_z       0
activity        0
dtype: int64

In [6]:
imu_columns = [
    "temperature",
    "acc16_x", "acc16_y", "acc16_z",
    "acc6_x", "acc6_y", "acc6_z",
    "gyro_x", "gyro_y", "gyro_z",
    "mag_x", "mag_y", "mag_z",
    "orientation_1", "orientation_2",
    "orientation_3", "orientation_4"
]

pamap2_columns = [
    "timestamp",
    "activity_id",
    "heart_rate"
]

for location in ["hand", "chest", "ankle"]:
    pamap2_columns += [
        f"{location}_{column}"
        for column in imu_columns
    ]

print("Number of column names:", len(pamap2_columns))

pamap2_sample.columns = pamap2_columns

display(pamap2_sample.head())

Number of column names: 54

,timestamp,activity_id,heart_rate,hand_temperature,hand_acc16_x,hand_acc16_y,hand_acc16_z,hand_acc6_x,hand_acc6_y,hand_acc6_z,...,ankle_gyro_x,ankle_gyro_y,ankle_gyro_z,ankle_mag_x,ankle_mag_y,ankle_mag_z,ankle_orientation_1,ankle_orientation_2,ankle_orientation_3,ankle_orientation_4
0,8.38,0,104.0,30.0,2.37223,8.60074,3.51048,2.43954,8.76165,3.35465,...,0.008300,0.009250,-0.017580,-61.1888,-38.9599,-58.1438,1.0,0.0,0.0,0.0
1,8.39,0,NaN,30.0,2.18837,8.56560,3.66179,2.39494,8.55081,3.64207,...,-0.006577,-0.004638,0.000368,-59.8479,-38.8919,-58.5253,1.0,0.0,0.0,0.0
2,8.40,0,NaN,30.0,2.37357,8.60107,3.54898,2.30514,8.53644,3.73280,...,0.003014,0.000148,0.022495,-60.7361,-39.4138,-58.3999,1.0,0.0,0.0,0.0
3,8.41,0,NaN,30.0,2.07473,8.52853,3.66021,2.33528,8.53622,3.73277,...,0.003175,-0.020301,0.011275,-60.4091,-38.7635,-58.3956,1.0,0.0,0.0,0.0
4,8.42,0,NaN,30.0,2.22936,8.83122,3.70000,2.23055,8.59741,3.76295,...,0.012698,-0.014303,-0.002823,-61.5199,-39.3879,-58.2694,1.0,0.0,0.0,0.0

In [7]:
print("Shape:", pamap2_sample.shape)

print("\nActivity IDs:")
print(
    pamap2_sample["activity_id"]
    .value_counts()
    .sort_index()
)

print("\nHeart rate:")
print(pamap2_sample["heart_rate"].describe())

print("\nMissing heart rate values:")
print(pamap2_sample["heart_rate"].isna().sum())

print("\nMissing heart rate (%):")
print(
    round(
        pamap2_sample["heart_rate"].isna().mean() * 100,
        2
    ),
    "%"
)

Shape: (376417, 54)

Activity IDs:
activity_id
0     126460
1      27187
2      23480
3      21717
4      22253
5      21265
6      23575
7      20265
12     15890
13     14899
16     22941
17     23573
24     12912
Name: count, dtype: int64

Heart rate:
count    34389.000000
mean       124.135479
std         24.000340
min         78.000000
25%        104.000000
50%        125.000000
75%        136.000000
max        183.000000
Name: heart_rate, dtype: float64

Missing heart rate values:
342028

Missing heart rate (%):
90.86 %

## Loading pipeline – all subjects

The following pipeline loads all subjects from PAMAP2 and MHEALTH
and adds a subject identifier to each observation.

In [8]:
# Load all PAMAP2 subjects

pamap2_data = []

for file in pamap2_files:
    df = pd.read_csv(
        file,
        sep=r"\s+",
        header=None,
        names=pamap2_columns
    )

    # subject101.dat -> 101
    subject_id = file.stem.replace("subject", "")
    df["subject_id"] = subject_id

    pamap2_data.append(df)

pamap2 = pd.concat(pamap2_data, ignore_index=True)

print("PAMAP2 successfully loaded")
print("Subjects:", pamap2["subject_id"].nunique())
print("Rows:", len(pamap2))
print("Columns:", pamap2.shape[1])
print("Activities:", sorted(pamap2["activity_id"].unique()))

PAMAP2 successfully loaded
Subjects: 9
Rows: 2872533
Columns: 55
Activities: [np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(12), np.int64(13), np.int64(16), np.int64(17), np.int64(24)]

In [9]:
# Load all MHEALTH subjects

mhealth_data = []

for file in mhealth_files:
    df = pd.read_csv(
        file,
        sep=r"\s+",
        header=None,
        names=mhealth_columns
    )

    # mHealth_subject1.log -> 1
    subject_id = file.stem.replace("mHealth_subject", "")
    df["subject_id"] = subject_id

    mhealth_data.append(df)

mhealth = pd.concat(mhealth_data, ignore_index=True)

print("MHEALTH successfully loaded")
print("Subjects:", mhealth["subject_id"].nunique())
print("Rows:", len(mhealth))
print("Columns:", mhealth.shape[1])
print("Activities:", sorted(mhealth["activity"].unique()))

MHEALTH successfully loaded
Subjects: 10
Rows: 1215745
Columns: 25
Activities: [np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12)]

In [10]:
# Loading pipeline summary

summary = pd.DataFrame({
    "Dataset": ["PAMAP2", "MHEALTH"],
    "Files loaded": [len(pamap2_files), len(mhealth_files)],
    "Subjects": [
        pamap2["subject_id"].nunique(),
        mhealth["subject_id"].nunique()
    ],
    "Rows": [
        len(pamap2),
        len(mhealth)
    ],
    "Columns": [
        pamap2.shape[1],
        mhealth.shape[1]
    ],
    "Activities": [
        pamap2["activity_id"].nunique(),
        mhealth["activity"].nunique()
    ]
})

display(summary)

   Dataset  Files loaded  Subjects     Rows  Columns  Activities
0   PAMAP2             9         9  2872533       55          13
1  MHEALTH            10        10  1215745       25          13

## CP1 – Temporal alignment and coverage report

The two datasets are aligned independently because they contain different participants.
The common analysis unit is person × temporal window.

For CP1, the goal is to align motion and cardiac information in time,
without extracting the final feature matrix yet.

In [12]:
%whos DataFrame

Variable         Type         Data/Info
---------------------------------------
df               DataFrame            chest_acc_x  ches<...>135168 rows x 25 columns]
mhealth          DataFrame             chest_acc_x  che<...>215745 rows x 25 columns]
mhealth_sample   DataFrame            chest_acc_x  ches<...>161280 rows x 24 columns]
pamap2           DataFrame             timestamp  activ<...>872533 rows x 55 columns]
pamap2_sample    DataFrame            timestamp  activi<...>376417 rows x 54 columns]
summary          DataFrame       Dataset  Files loaded <...>5745       25          13

In [14]:
print(pamap2.columns.tolist())

['timestamp', 'activity_id', 'heart_rate', 'hand_temperature', 'hand_acc16_x', 'hand_acc16_y', 'hand_acc16_z', 'hand_acc6_x', 'hand_acc6_y', 'hand_acc6_z', 'hand_gyro_x', 'hand_gyro_y', 'hand_gyro_z', 'hand_mag_x', 'hand_mag_y', 'hand_mag_z', 'hand_orientation_1', 'hand_orientation_2', 'hand_orientation_3', 'hand_orientation_4', 'chest_temperature', 'chest_acc16_x', 'chest_acc16_y', 'chest_acc16_z', 'chest_acc6_x', 'chest_acc6_y', 'chest_acc6_z', 'chest_gyro_x', 'chest_gyro_y', 'chest_gyro_z', 'chest_mag_x', 'chest_mag_y', 'chest_mag_z', 'chest_orientation_1', 'chest_orientation_2', 'chest_orientation_3', 'chest_orientation_4', 'ankle_temperature', 'ankle_acc16_x', 'ankle_acc16_y', 'ankle_acc16_z', 'ankle_acc6_x', 'ankle_acc6_y', 'ankle_acc6_z', 'ankle_gyro_x', 'ankle_gyro_y', 'ankle_gyro_z', 'ankle_mag_x', 'ankle_mag_y', 'ankle_mag_z', 'ankle_orientation_1', 'ankle_orientation_2', 'ankle_orientation_3', 'ankle_orientation_4', 'subject_id']

In [15]:
# CP1 - PAMAP2 temporal alignment

WINDOW_SECONDS = 5

pamap2_aligned = pamap2.copy()

# Activity 0 = transient / undefined activity -> exclude
pamap2_aligned = pamap2_aligned[
    pamap2_aligned["activity_id"] != 0
].copy()

# Create a 5-second temporal grid for each subject
pamap2_aligned["window_id"] = (
    pamap2_aligned["timestamp"] // WINDOW_SECONDS
).astype(int)

# Interpolate heart rate independently for each subject
pamap2_aligned["heart_rate_aligned"] = (
    pamap2_aligned
    .groupby("subject_id")["heart_rate"]
    .transform(lambda x: x.interpolate(limit_direction="both"))
)

print("PAMAP2 rows after removing activity 0:", len(pamap2_aligned))

print(
    "Missing HR before alignment:",
    f"{pamap2_aligned['heart_rate'].isna().mean() * 100:.2f}%"
)

print(
    "Missing HR after alignment:",
    f"{pamap2_aligned['heart_rate_aligned'].isna().mean() * 100:.2f}%"
)

pamap2_aligned[
    [
        "subject_id",
        "timestamp",
        "window_id",
        "activity_id",
        "heart_rate",
        "heart_rate_aligned"
    ]
].head(15)

PAMAP2 rows after removing activity 0: 1942872
Missing HR before alignment: 90.87%
Missing HR after alignment: 0.00%

,subject_id,timestamp,window_id,activity_id,heart_rate,heart_rate_aligned
2928,101,37.66,7,1,NaN,100.0
2929,101,37.67,7,1,NaN,100.0
2930,101,37.68,7,1,NaN,100.0
2931,101,37.69,7,1,NaN,100.0
2932,101,37.70,7,1,100.0,100.0
2933,101,37.71,7,1,NaN,100.0
2934,101,37.72,7,1,NaN,100.0
2935,101,37.73,7,1,NaN,100.0
2936,101,37.74,7,1,NaN,100.0
2937,101,37.75,7,1,NaN,100.0
2938,101,37.76,7,1,NaN,100.0
2939,101,37.77,7,1,NaN,100.0
2940,101,37.78,7,1,NaN,100.0
2941,101,37.79,7,1,NaN,100.0
2942,101,37.80,7,1,NaN,100.0

In [16]:
# CP1 - PAMAP2 aligned window table

pamap2_windows = (
    pamap2_aligned
    .groupby(["subject_id", "window_id"])
    .agg(
        start_time=("timestamp", "min"),
        end_time=("timestamp", "max"),
        activity_id=("activity_id", lambda x: x.mode().iloc[0]),
        imu_samples=("timestamp", "size"),
        hr_raw_samples=("heart_rate", "count"),
        heart_rate=("heart_rate_aligned", "mean")
    )
    .reset_index()
)

# Coverage: a valid aligned window contains motion samples
# and cardiac information after temporal alignment
pamap2_windows["has_motion"] = pamap2_windows["imu_samples"] > 0
pamap2_windows["has_cardiac"] = pamap2_windows["heart_rate"].notna()
pamap2_windows["complete_multimodal"] = (
    pamap2_windows["has_motion"] &
    pamap2_windows["has_cardiac"]
)

print("PAMAP2 aligned table")
print("Unit: subject × 5-second window")
print("Total windows:", len(pamap2_windows))
print(
    "Complete multimodal windows:",
    pamap2_windows["complete_multimodal"].sum()
)
print(
    "Coverage:",
    f"{pamap2_windows['complete_multimodal'].mean() * 100:.2f}%"
)

pamap2_windows.head(10)

PAMAP2 aligned table
Unit: subject × 5-second window
Total windows: 3974
Complete multimodal windows: 3974
Coverage: 100.00%

,subject_id,window_id,start_time,end_time,activity_id,imu_samples,hr_raw_samples,heart_rate,has_motion,has_cardiac,complete_multimodal
0,101,7,37.66,39.99,1,234,21,100.884615,True,True,True
1,101,8,40.00,44.99,1,500,46,102.000000,True,True,True
2,101,9,45.00,49.99,1,500,46,102.738000,True,True,True
3,101,10,50.00,54.99,1,500,46,105.416000,True,True,True
4,101,11,55.00,59.99,1,500,45,106.264000,True,True,True
5,101,12,60.00,64.99,1,500,46,103.554000,True,True,True
6,101,13,65.00,69.99,1,500,46,99.924000,True,True,True
7,101,14,70.00,74.99,1,500,45,96.506000,True,True,True
8,101,15,75.00,79.99,1,500,46,94.318000,True,True,True
9,101,16,80.00,84.99,1,500,46,93.194000,True,True,True

In [17]:
print(mhealth.columns.tolist())

['chest_acc_x', 'chest_acc_y', 'chest_acc_z', 'ecg_lead_1', 'ecg_lead_2', 'ankle_acc_x', 'ankle_acc_y', 'ankle_acc_z', 'ankle_gyro_x', 'ankle_gyro_y', 'ankle_gyro_z', 'ankle_mag_x', 'ankle_mag_y', 'ankle_mag_z', 'arm_acc_x', 'arm_acc_y', 'arm_acc_z', 'arm_gyro_x', 'arm_gyro_y', 'arm_gyro_z', 'arm_mag_x', 'arm_mag_y', 'arm_mag_z', 'activity', 'subject_id']

In [18]:
# CP1 - MHEALTH temporal alignment

WINDOW_SECONDS = 5
MHEALTH_HZ = 50
SAMPLES_PER_WINDOW = WINDOW_SECONDS * MHEALTH_HZ  # 250

mhealth_aligned = mhealth.copy()

# Activity 0 = null / transition periods -> exclude
mhealth_aligned = mhealth_aligned[
    mhealth_aligned["activity"] != 0
].copy()

# Rebuild sample position independently for each subject
mhealth_aligned["sample_id"] = (
    mhealth_aligned
    .groupby("subject_id")
    .cumcount()
)

# Temporal grid: 250 samples = 5 seconds at 50 Hz
mhealth_aligned["window_id"] = (
    mhealth_aligned["sample_id"] // SAMPLES_PER_WINDOW
).astype(int)

# Check availability of motion and ECG at sample level
motion_cols = ["chest_acc_x", "chest_acc_y", "chest_acc_z"]
ecg_cols = ["ecg_lead_1", "ecg_lead_2"]

mhealth_aligned["motion_valid"] = (
    mhealth_aligned[motion_cols].notna().all(axis=1)
)

mhealth_aligned["ecg_valid"] = (
    mhealth_aligned[ecg_cols].notna().all(axis=1)
)

print("MHEALTH rows after removing activity 0:", len(mhealth_aligned))
print(
    "Missing motion samples:",
    f"{(1 - mhealth_aligned['motion_valid'].mean()) * 100:.2f}%"
)
print(
    "Missing ECG samples:",
    f"{(1 - mhealth_aligned['ecg_valid'].mean()) * 100:.2f}%"
)

MHEALTH rows after removing activity 0: 343195
Missing motion samples: 0.00%
Missing ECG samples: 0.00%

In [19]:
# Build aligned table: one row = subject × 5-second window

mhealth_windows = (
    mhealth_aligned
    .groupby(["subject_id", "window_id"])
    .agg(
        activity=("activity", lambda x: x.mode().iloc[0]),
        samples=("sample_id", "size"),
        motion_samples=("motion_valid", "sum"),
        ecg_samples=("ecg_valid", "sum")
    )
    .reset_index()
)

# A full 5-second MHEALTH window contains 250 samples
mhealth_windows["full_window"] = (
    mhealth_windows["samples"] == SAMPLES_PER_WINDOW
)

mhealth_windows["complete_multimodal"] = (
    (mhealth_windows["motion_samples"] == mhealth_windows["samples"]) &
    (mhealth_windows["ecg_samples"] == mhealth_windows["samples"])
)

print("\nMHEALTH aligned table")
print("Unit: subject × 5-second window")
print("Total windows:", len(mhealth_windows))
print("Full 5-second windows:", mhealth_windows["full_window"].sum())
print(
    "Complete multimodal windows:",
    mhealth_windows["complete_multimodal"].sum()
)
print(
    "Multimodal coverage:",
    f"{mhealth_windows['complete_multimodal'].mean() * 100:.2f}%"
)

mhealth_windows.head(10)

MHEALTH aligned table
Unit: subject × 5-second window
Total windows: 1378
Full 5-second windows: 1368
Complete multimodal windows: 1378
Multimodal coverage: 100.00%

,subject_id,window_id,activity,samples,motion_samples,ecg_samples,full_window,complete_multimodal
0,1,0,1,250,250,250,True,True
1,1,1,1,250,250,250,True,True
2,1,2,1,250,250,250,True,True
3,1,3,1,250,250,250,True,True
4,1,4,1,250,250,250,True,True
5,1,5,1,250,250,250,True,True
6,1,6,1,250,250,250,True,True
7,1,7,1,250,250,250,True,True
8,1,8,1,250,250,250,True,True
9,1,9,1,250,250,250,True,True

In [20]:
# CP1 - Final alignment coverage report

# PAMAP2: full 5-second window = 500 IMU samples
pamap2_windows["full_window"] = (
    pamap2_windows["imu_samples"] == 500
)

pamap2_valid = pamap2_windows[
    pamap2_windows["full_window"] &
    pamap2_windows["complete_multimodal"]
].copy()

# MHEALTH: full 5-second window = 250 samples
mhealth_valid = mhealth_windows[
    mhealth_windows["full_window"] &
    mhealth_windows["complete_multimodal"]
].copy()

coverage_report = pd.DataFrame({
    "Dataset": ["PAMAP2", "MHEALTH"],
    "Subjects": [
        pamap2_valid["subject_id"].nunique(),
        mhealth_valid["subject_id"].nunique()
    ],
    "Total windows": [
        len(pamap2_windows),
        len(mhealth_windows)
    ],
    "Full 5s windows": [
        pamap2_windows["full_window"].sum(),
        mhealth_windows["full_window"].sum()
    ],
    "Final aligned windows": [
        len(pamap2_valid),
        len(mhealth_valid)
    ],
    "Coverage (%)": [
        len(pamap2_valid) / len(pamap2_windows) * 100,
        len(mhealth_valid) / len(mhealth_windows) * 100
    ]
})

coverage_report["Coverage (%)"] = (
    coverage_report["Coverage (%)"].round(2)
)

coverage_report

,Dataset,Subjects,Total windows,Full 5s windows,Final aligned windows,Coverage (%)
0,PAMAP2,9,3974,3805,3805,95.75
1,MHEALTH,10,1378,1368,1368,99.27

In [21]:
# CP1 - Examples of the final aligned unit × time tables

pamap2_cp1_table = pamap2_valid[
    [
        "subject_id",
        "window_id",
        "start_time",
        "end_time",
        "activity_id",
        "imu_samples",
        "hr_raw_samples",
        "heart_rate"
    ]
].copy()

mhealth_cp1_table = mhealth_valid[
    [
        "subject_id",
        "window_id",
        "activity",
        "samples",
        "motion_samples",
        "ecg_samples"
    ]
].copy()

print("PAMAP2 – aligned table (one row = subject × 5 s)")
display(pamap2_cp1_table.head())

print("\nMHEALTH – aligned table (one row = subject × 5 s)")
display(mhealth_cp1_table.head())

PAMAP2 – aligned table (one row = subject × 5 s)

,subject_id,window_id,start_time,end_time,activity_id,imu_samples,hr_raw_samples,heart_rate
1,101,8,40.0,44.99,1,500,46,102.000
2,101,9,45.0,49.99,1,500,46,102.738
3,101,10,50.0,54.99,1,500,46,105.416
4,101,11,55.0,59.99,1,500,45,106.264
5,101,12,60.0,64.99,1,500,46,103.554

MHEALTH – aligned table (one row = subject × 5 s)

  subject_id  window_id  activity  samples  motion_samples  ecg_samples
0          1          0         1      250             250          250
1          1          1         1      250             250          250
2          1          2         1      250             250          250
3          1          3         1      250             250          250
4          1          4         1      250             250          250

In [22]:
# CP1 - Final aligned tables
# One row = subject × 5-second window

pamap2_cp1_table = pamap2_valid[
    [
        "subject_id",
        "window_id",
        "start_time",
        "end_time",
        "activity_id",
        "imu_samples",
        "hr_raw_samples",
        "heart_rate"
    ]
].copy()

mhealth_cp1_table = mhealth_valid[
    [
        "subject_id",
        "window_id",
        "activity",
        "samples",
        "motion_samples",
        "ecg_samples"
    ]
].copy()

print("PAMAP2 – aligned table (one row = subject × 5 s)")
display(pamap2_cp1_table.head())

print("\nMHEALTH – aligned table (one row = subject × 5 s)")
display(mhealth_cp1_table.head())

PAMAP2 – aligned table (one row = subject × 5 s)

,subject_id,window_id,start_time,end_time,activity_id,imu_samples,hr_raw_samples,heart_rate
1,101,8,40.0,44.99,1,500,46,102.000
2,101,9,45.0,49.99,1,500,46,102.738
3,101,10,50.0,54.99,1,500,46,105.416
4,101,11,55.0,59.99,1,500,45,106.264
5,101,12,60.0,64.99,1,500,46,103.554

MHEALTH – aligned table (one row = subject × 5 s)

  subject_id  window_id  activity  samples  motion_samples  ecg_samples
0          1          0         1      250             250          250
1          1          1         1      250             250          250
2          1          2         1      250             250          250
3          1          3         1      250             250          250
4          1          4         1      250             250          250